sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t eh-telo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eh-telo/docker-react npm run test -- --coverage
